---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: archlinux
    image: archlinux:20200106
playbooks:
  prepare: prepare.yml
provisioner:
  name: ansible
verifier:
  name: testinfra
