---
# tasks file for build
- name: Ensure directories exist
  file:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  loop:
    - path: /etc/sudoers.d
      state: directory
      owner: root
      group: root
      mode: '0755'

- name: Create build user and home directory
  user:
    name: '{{ build_user }}'
    create_home: true
    home: '{{ build_user_home }}'

- name: Copy build files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
  loop:
    - src: bashrc
      dest: '{{ build_user_home }}/.bashrc'
      mode: '0600'
      owner: '{{ build_user }}'
      group: '{{ build_group }}'
    - src: bash_profile
      dest: '{{ build_user_home }}/.bash_profile'
      mode: '0600'
      owner: '{{ build_user }}'
      group: '{{ build_group }}'
    - src: evergreen.yml
      dest: '{{ build_user_home }}/.evergreen.yml'
      mode: '0600'
      owner: '{{ build_user }}'
      group: '{{ build_group }}'
    - src: dmesg
      dest: /etc/sudoers.d/dmesg
      mode: '0440'
      owner: root
      group: root

- name: Check if cloud-init config is present
  stat:
    path: /etc/cloud/cloud.cfg
  register: cloud

- name: Disable cloud-init hosts file management
  lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^ - update_etc_hosts'
    state: absent
  when: cloud.stat.exists
