---
# tasks file for build
- name: Ensure directories exist
  become: true
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - path: /etc/sudoers.d
      state: directory
      owner: root
      group: root
      mode: "0755"

- name: Copy build files
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
  loop:
    - src: bashrc
      dest: "~{{ build_user }}/.bashrc"
      mode: "0600"
      owner: "{{ build_user }}"
    - src: bash_profile
      dest: "~{{ build_user }}/.bash_profile"
      mode: "0600"
      owner: "{{ build_user }}"
    - src: dmesg
      dest: /etc/sudoers.d/dmesg
      mode: "0440"
      owner: root
    - src: mongodb-build-system-id
      dest: /etc/mongodb-build-system-id
      mode: "0644"
      owner: root
